const data = [
    {
        id: 1,
        img: "/assets/img/lenevoimg1.webp",
        img2: "../assets/img/lenevoimg1hover.webp",
        brand: "LENEVO",
        title: "Lenovo LP6 TWS Gaming Noise cancelling Earbuds",
        price: 5500,
        delprice: 8000,
        images: [
            "../assets/img/lenevoimg1hover.webp",
            "../assets/img/lenevoimg1hover.webp",
            "../assets/img/lenevoimg1hover.webp",
            "../assets/img/lenevoimg1hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 2,
        img: "../assets/img/lenevoimg2.webp",
        img2: "../assets/img/lenevoimg2hover.webp",
        brand: "LENEVO",
        title: "Lenovo LP5 TWS Bluetooth 5.0 Earbuds",
        price: 3750,
        delprice: 5000,
        images: [
            "../assets/img/lenevoimg2hover.webp",
            "../assets/img/lenevoimg2hover.webp",
            "../assets/img/lenevoimg2hover.webp",
            "../assets/img/lenevoimg2hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 3,
        img: "../assets/img/lenevoimg3.webp",
        img2: "../assets/img/lenevoimg3hover.webp",
        brand: "LENEVO",
        title: "Lenovo Thinkplus XT95 Pro Bluetooth Earphone 9D HIFI Sound (Luminous Version)",
        price: 3750,
        delprice: 7000,
        images: [
            "../assets/img/lenevoimg3hover.webp",
            "../assets/img/lenevoimg3hover.webp",
            "../assets/img/lenevoimg3hover.webp",
            "../assets/img/lenevoimg3hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 4,
        img: "../assets/img/lenevoimg4.webp",
        img2: "../assets/img/lenevoimg4hover.webp",
        brand: "LENEVO",
        title: "Lenovo XT80 Bluetooth 5.3 Wireless Earphones with Mic Button Noise Reduction",
        price: 7000,
        delprice: 10000,
        images: [
            "../assets/img/lenevoimg4hover.webp",
            "../assets/img/lenevoimg4hover.webp",
            "../assets/img/lenevoimg4hover.webp",
            "../assets/img/lenevoimg4hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 5,
        img: "../assets/img/lenevoimg5.webp",
        img2: "../assets/img/lenevoimg5hover.webp",
        brand: "LENEVO",
        title: "Lenovo TW60 Bluetooth 5.3 Noise Reduction Earbuds",
        price: 6500,
        delprice: 8000,
        images: [
            "../assets/img/lenevoimg5hover.webp",
            "../assets/img/lenevoimg5hover.webp",
            "../assets/img/lenevoimg5hover.webp",
            "../assets/img/lenevoimg5hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 6,
        img: "../assets/img/lenevoimg6.webp",
        img2: "../assets/img/lenevoimg6hover.webp",
        brand: "LENEVO",
        title: "Lenovo LP19 Bluetooth 5.3 Sports Noise Reduction Earbuds",
        price: 4500,
        delprice: 8000,
        images: [
            "../assets/img/lenevoimg6hover.webp",
            "../assets/img/lenevoimg6hover.webp",
            "../assets/img/lenevoimg6hover.webp",
            "../assets/img/lenevoimg6hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 7,
        img: "../assets/img/monsterimg1.webp",
        img2: "../assets/img/monsterimg1hover.webp",
        brand: "MONSTER",
        title: "Lenovo Monster XKT12 Bluetooth 5.3 Gaming Earbuds",
        price: 4750,
        delprice: 8000,
        images: [
            "../assets/img/monsterimg1hover.webp",
            "../assets/img/monsterimg1hover.webp",
            "../assets/img/monsterimg1hover.webp",
            "../assets/img/monsterimg1hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
    {
        id: 8,
        img: "../assets/img/monsterimg2.webp",
        img2: "../assets/img/monsterimg2hover.webp",
        brand: "MONSTER",
        title: "Lenovo Monster XKT16 Bluetooth 5.3 Earphone",
        price: 4750,
        delprice: 8000,
        images: [
            "../assets/img/monsterimg2hover.webp",
            "../assets/img/monsterimg2hover.webp",
            "../assets/img/monsterimg2hover.webp",
            "../assets/img/monsterimg2hover.webp",
        ],
        description: "Gaming-grade gaming Bluetooth Three- frequency balanced analysis, 13mm vivid diaphragm Using 7.1 channels, the bass resonates with the ear at the same frequency, and the shock is even Long battery life, large - capacity charging compartment, noise reduction for calls Wearing method: in -ear Horn diameter: Φ 13mm Speaker material: composite membrane Headphone battery capacity: 35 mAh Power - on battery life: about 3H Headphone talk time: about 4H Support audio format: SBC ACC Operation method: touch",
    },
]
export default data